Supermarket/config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resource :carts, only: [:show]

       root to: 'pages#home'
  devise_for :users
  resources :products do
    collection do
      get 'search'
    end
  end

  #root 'products#index'
end

Supermarket/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Supermarket/app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

Supermarket/app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items

  before_save :set_subtotal

  def subtotal
    order_items.collect {|order_item| order_item.valid? ? (order_item.unit_price*order_item.quantity) : 0}.sum
  end

  private
    def set_subtotal
      self[:subtotal] = subtotal
    end
end

Supermarket/app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

    def set_unit_price
      self[:unit_price] = unit_price
    end

    def set_total_price
      self[:total_price] = quantity * set_unit_price

    end
end

Supermarket/app/models/product.rb
class Product < ApplicationRecord
  has_attached_file :image, styles: { medium: "200x200#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  searchkick
  belongs_to :category
  has_many :order_items
end

Supermarket/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Supermarket/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

   include ApplicationHelper
end

Supermarket/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

Supermarket/app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end

  private

    def order_item_params
      params.require(:order_item).permit(:product_id, :quantity)
    end

end

Supermarket/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if !current_user.nil?
      redirect_to products_path
    end
  end
end

Supermarket/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  def search
    if params[:search].present?
      @products = Product.search(params[:search])
    else
      @products = Product.all
    end
  end

  def index

    if params[:category].blank?
      @products = Product.all
    else
      @category_id =Category.find_by(name: params[:category]).id
      @products = Product.where(category_id: @category_id)
    end

    @order_item = current_order.order_items.new
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(products_params)
    #@product.user = current_user

    if @product.save
      redirect_to @product
    else
      render "New"
    end
  end

  def edit
  end

  def update
    if @product.update(products_params)
      redirect_to @product
    else
      render "Editar"
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

  def products_params
    params.require(:product).permit(:name, :price, :mark, :category_id, :image)
  end

  def find_product
    @product = Product.find(params[:id])
  end
end

Supermarket/app/helpers/application_helper.rb
module ApplicationHelper

  def current_order

    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end

  end

end

Supermarket/app/helpers/carts_helper.rb
module CartsHelper
end

Supermarket/app/helpers/order_items_helper.rb
module OrderItemsHelper
end

Supermarket/app/helpers/pages_helper.rb
module PagesHelper
end

Supermarket/app/helpers/products_helper.rb
module ProductsHelper
end

Supermarket/app/views/carts/_cart_item.haml
- if !@order_item.nil? && @order_item.errors.any?
  %ul
    - @order_item.errors.full_messages.each do |msg|
      %li= msg
- if @order_items.size>0
  - @order_items.each do |item|
    .well
      .row
        .col-sm-8
          %h3= item.product.name
        .col-sm-4
          .pull-right
            = form_for(item, remote: true) do |f|
              = f.hidden_field :product_id, value: item.product.id
              %h5= item.product.price
              .form-group
                = f.text_field :quantity, value: item.quantity.to_i, min: 1, class: 'form-control'
              .btn-group
                = f.submit "Adicionar", class: 'btn btn-primary'
                = link_to "Deletar", item, method: :delete, remote: true, class: 'btn btn-danger'
              %span
                Valor: R$
                = item.total_price
- else

Supermarket/app/views/carts/show.html.haml
.cart_ite
  = render 'carts/cart_item'

Supermarket/app/views/layouts/_alerts.html.haml
%p.notice= notice
%p.alert= alert

Supermarket/app/views/layouts/_cart.html.haml
= link_to "Carrinho R$: #{current_order.subtotal}", carts_path

Supermarket/app/views/layouts/application.html.haml
!!!
%html
%head
  %title Supermarket
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  - if current_user
    %nav.navbar.navbar-default
      .container
        .navbar-brand Compras
        %ul.nav.navbar-nav
          %li= link_to "Home", products_path

          - Category.all.each do |category|
            %li= link_to category.name, products_path(category: category.name)
          .fixed
            = link_to 'Sair', destroy_user_session_path, method: :delete

          %li.active.cart
            = render 'layouts/cart'
        - if current_user && current_user.admin
          = link_to "Novo Produto", new_product_path, class: "navbar-text navbar-right navbar-link"

        = form_tag search_products_path, method: :get, class: "navbar-form navbar-left", role: "search" do
          = text_field_tag :search, params[:search], class: "form-control", placeholder: "Pesquisar"

  - else
    = render 'pages/inicio'
  .container
    = render 'layouts/alerts'
    = yield

Supermarket/app/views/order_items/create.js.haml
- if @order.errors.any? || @order_item.errors.any?
  alert("Invalid")
- else
  $(".cart").html("= escape_javascript(render 'layouts/cart')")

Supermarket/app/views/order_items/destroy.js.haml
$(".cart").html("= escape_javascript(render 'layouts/cart')")
$(".cart_item").html("= escape_javascript(render 'carts/cart_item')")

Supermarket/app/views/pages/home.html.haml
#products
  .product
    %h2 Supermarket

- if current_user
  = link_to 'Sair', destroy_user_session_path, method: :delete
- else
  = link_to 'Registrar', new_user_registration_path, class: "btn btn-sn btn-default"
  = link_to 'Entrar', new_user_session_path, class: "btn btn-sn btn-default"

- if current_user && current_user.admin
  = link_to 'Ir as compras', products_path

Supermarket/app/views/products/_form.html.haml
= simple_form_for(@product, html: { class: 'form-horizontal'}) do |f|
  = f.collection_select :category_id, Category.all, :id, :name, {pront: "Escolha uma categoria" }
  = f.input :name, label: "Nome"
  = f.input :price, label: "Preço"
  = f.input :mark, label: "Marca"
  = f.input :image
  %br/
  = f.button :submit

Supermarket/app/views/products/edit.html.haml
%h1 Editar Produto

= render 'form'

= link_to "Back", products_path

Supermarket/app/views/products/index.html.haml
.row
  #products
    - @products.each do |product|
      .col-md-3
        .product
          .image
            = link_to product do
              = image_tag product.image.url(:medium)
          .product
          %h2= link_to product.name, product
          %p= product.mark
          %p= product.price

        = form_for(@order_item, remote: true) do |f|
          = f.hidden_field :product_id, value: product.id
          .form-group
            = f.text_field :quantity, value: 1, min: 1, class: 'form-control'
          = f.submit "Adicionar ao carrinho", class: 'btn btn-primary btn-sm'

Supermarket/app/views/products/new.html.haml
%h1 Novo Produto

= render 'form'

= link_to "Back", products_path

Supermarket/app/views/products/search.html.haml
#products
  - @products.each do |product|
    .col-md-3
      .product
        .image
          = link_to product do
            = image_tag product.image.url(:medium)

        %h2= link_to product.name, product
        %p= product.mark
        %p= product.price

Supermarket/app/views/products/show.html.haml
#products
  .product
    .image
      = image_tag @product.image.url(:medium, class: "product_image")
  .product
    %h2= @product.name
    %p= @product.mark
    %p= @product.price

= link_to "Home", products_path, class: "btn btn-sn btn-default"
- if current_user && current_user.admin
  = link_to "Editar", edit_product_path(@product), class: "btn btn-sn btn-default"
  = link_to "Deletar", product_path(@product), method: :delete, data: { confirm: "Você tem certeza?" }, class: "btn btn-sn btn-default"